= Projektantrag
Moritz Eder
1.0.0, 2021/22,
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Projektbezeichnung

Diagram Generator

== Projektauftraggeber

Moritz Eder

== Projekthintergrund

Ich will einen Diagramm Generator machen, der dem User eine einfache Möglichkeit geben soll, Diagramme zu erstellen.

== Projektziele

=== Sinn/Zweck

Dieser Generator soll eine einfache und schnelle Lösung zum Erstellen von Diagrammen sein. Es sollte auch für Personen, die sich nicht so gut auskennen, kein Problem darstellen, ein Diagramm zu machen.

=== Kunde/Beteiligte

Es wird für jeden im Internet zugägnlich sein.

=== Endergebnis

Ein vollständiger Generator mit vielen Eingabemöglichkeiten sollte bis spätestens Ende des Schuljahres fertig sein.

=== Kriterien

. Funktioniert die Eingabe?
. Ist es übersichtlich gestaltet?
. Ist die Ausgabe gut leserlich gestaltet?
. Ist es benutzerfreundlich?

